name: VisionFX Publish

on:
  push:
    branches: ['master']
    paths: ['docker/VisionFXContainer/Dockerfile']
jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' 
    steps:
        - uses: actions/checkout@v2 
        - name: Build and Publish latest Docker image
          uses: VaultVulp/gp-docker-action@1.1.12
          with:
            github-token: ${{ secrets.PACKAGES_GITHUB_TOKEN }}
            image-name: VisionFX-DevContainer
            dockerfile: docker/VisionFXContainer/Dockerfile
